version: '3.8'

services:
  agent6:
    build: .
    container_name: p2p_agent_6
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    cap_add:
      - NET_ADMIN
    privileged: true

  agent7:
    build: .
    container_name: p2p_agent_7
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    command: sh -c "sleep 1 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent8:
    build: .
    container_name: p2p_agent_8
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    command: sh -c "sleep 2 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent9:
    build: .
    container_name: p2p_agent_9
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    command: sh -c "sleep 3 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  p2p_net:
    external: true
