version: '3.8'

services:
  agent6:
    build: .
    container_name: p2p_agent_6
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=6  
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=2
    cap_add:
      - NET_ADMIN
    privileged: true

  agent7:
    build: .
    container_name: p2p_agent_7
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=7
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=2
    command: sh -c "sleep 1 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent8:
    build: .
    container_name: p2p_agent_8
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=8
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=2
    command: sh -c "sleep 2 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent9:
    build: .
    container_name: p2p_agent_9
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=9
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=2
    command: sh -c "sleep 3 && ./agent"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent10:
      build: .
      container_name: p2p_agent_10
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=10
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=2
      command: sh -c "sleep 4 && ./agent"
      cap_add:
        - NET_ADMIN
      privileged: true

  agent11:
      build: .
      container_name: p2p_agent_11
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=11
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=2
      command: sh -c "sleep 5 && ./agent"
      cap_add:
        - NET_ADMIN
      privileged: true

networks:
  p2p_net:
    external: true
  presentation_net:
    external: true
