version: '3.8'

services:
  agent2:
    build: .
    container_name: p2p_agent_2
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    ports:
      - "5002:5000/tcp"
      - "5002:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent3:
    build: .
    container_name: p2p_agent_3
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    ports:
      - "5003:5000/tcp"
      - "5003:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent4:
    build: .
    container_name: p2p_agent_4
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    ports:
      - "5004:5000/tcp"
      - "5004:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent5:
    build: .
    container_name: p2p_agent_5
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - MAX_PEERS=2
    ports:
      - "5005:5000/tcp"
      - "5005:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  p2p_net:
    external: true
