version: '3.8'

services:
  agent4:
    build: .
    container_name: p2p_agent_4
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=p2p_agent_1
      - MAX_PEERS=2
    ports:
      - "5004:5000/tcp"
      - "5004:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent5:
    build: .
    container_name: p2p_agent_5
    networks:
      - p2p_net
    environment:
      - BOOTSTRAP_IP=p2p_agent_1
      - MAX_PEERS=2
    ports:
      - "5005:5000/tcp"
      - "5005:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  p2p_net:
    driver: bridge
