version: '3.8'

services:
  agent2:
    build: .
    container_name: p2p_agent_2
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=2
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    ports:
      - "5002:5000/tcp"
      - "5002:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent3:
    build: .
    container_name: p2p_agent_3
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=3
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 2 && ./agent"
    ports:
      - "5003:5000/tcp"
      - "5003:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent4:
    build: .
    container_name: p2p_agent_4
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=4
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 3 && ./agent"
    ports:
      - "5004:5000/tcp"
      - "5004:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent5:
    build: .
    container_name: p2p_agent_5
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=5
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 4 && ./agent"
    ports:
      - "5005:5000/tcp"
      - "5005:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
  
  agent6:
    build: .
    container_name: p2p_agent_6
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=6  
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 5 && ./agent"
    ports:
      - "5006:5000/tcp"
      - "5006:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent7:
    build: .
    container_name: p2p_agent_7
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=7
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 6 && ./agent"
    ports:
      - "5007:5000/tcp"
      - "5007:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent8:
    build: .
    container_name: p2p_agent_8
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=8
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 7 && ./agent"
    ports:
      - "5008:5000/tcp"
      - "5008:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent9:
    build: .
    container_name: p2p_agent_9
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=9
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 8 && ./agent"
    ports:
      - "5009:5000/tcp"
      - "5009:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent10:
      build: .
      container_name: p2p_agent_10
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=10
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=3
      command: sh -c "sleep 9 && ./agent"
      ports:
      - "5010:5000/tcp"
      - "5010:5000/udp"
      cap_add:
        - NET_ADMIN
      privileged: true

  agent11:
      build: .
      container_name: p2p_agent_11
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=11
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=3
      command: sh -c "sleep 10 && ./agent"
      ports:
      - "5011:5000/tcp"
      - "5011:5000/udp"
      cap_add:
        - NET_ADMIN
      privileged: true
  agent12:
      build: .
      container_name: p2p_agent_12
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=12
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=3
      command: sh -c "sleep 11 && ./agent"
      ports:
      - "5012:5000/tcp"
      - "5012:5000/udp"
      cap_add:
        - NET_ADMIN
      privileged: true

  agent13:
      build: .
      container_name: p2p_agent_13
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=13
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=3
      command: sh -c "sleep 12 && ./agent"
      ports:
      - "5013:5000/tcp"
      - "5013:5000/udp"
      cap_add:
        - NET_ADMIN
      privileged: true
  
  agent14:
      build: .
      container_name: p2p_agent_14
      networks:
        - p2p_net
        - presentation_net
      environment:
        - AGENT_ID=14
        - BOOTSTRAP_IP=172.18.0.2
        - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
        - REPORT_URL=http://172.20.0.3:8080/report
        - PEERS_LIMIT=3
      command: sh -c "sleep 14 && ./agent"
      ports:
      - "5014:5000/tcp"
      - "5014:5000/udp"
      cap_add:
        - NET_ADMIN
      privileged: true
  
  agent15:
    build: .
    container_name: p2p_agent_15
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=15
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 15 && ./agent"
    ports:
      - "5015:5000/tcp"
      - "5015:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent16:
    build: .
    container_name: p2p_agent_16
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=16
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 16 && ./agent"
    ports:
      - "5016:5000/tcp"
      - "5016:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent17:
    build: .
    container_name: p2p_agent_17
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=17
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 17 && ./agent"
    ports:
      - "5017:5000/tcp"
      - "5017:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent18:
    build: .
    container_name: p2p_agent_18
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=18
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 18 && ./agent"
    ports:
      - "5018:5000/tcp"
      - "5018:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent19:
    build: .
    container_name: p2p_agent_19
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=19
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 19 && ./agent"
    ports:
      - "5019:5000/tcp"
      - "5019:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent20:
    build: .
    container_name: p2p_agent_20
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=20
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 20 && ./agent"
    ports:
      - "5020:5000/tcp"
      - "5020:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent21:
    build: .
    container_name: p2p_agent_21
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=21
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 21 && ./agent"
    ports:
      - "5021:5000/tcp"
      - "5021:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent22:
    build: .
    container_name: p2p_agent_22
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=22
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 22 && ./agent"
    ports:
      - "5022:5000/tcp"
      - "5022:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent23:
    build: .
    container_name: p2p_agent_23
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=23
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 23 && ./agent"
    ports:
      - "5023:5000/tcp"
      - "5023:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent24:
    build: .
    container_name: p2p_agent_24
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=24
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 24 && ./agent"
    ports:
      - "5024:5000/tcp"
      - "5024:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

  agent25:
    build: .
    container_name: p2p_agent_25
    networks:
      - p2p_net
      - presentation_net
    environment:
      - AGENT_ID=25
      - BOOTSTRAP_IP=172.18.0.2
      - BOOTSTRAP_PEER_ID=12D3KooWSHB3WLC7CcZubYJ8e2Z4N6ewDHEEbWrNTrTwpqJqJ7jR
      - REPORT_URL=http://172.20.0.3:8080/report
      - PEERS_LIMIT=3
    command: sh -c "sleep 25 && ./agent"
    ports:
      - "5025:5000/tcp"
      - "5025:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  p2p_net:
    external: true
  presentation_net:
    external: true
