version: '3.8'

services:
  agent1:
    build: .
    container_name: p2p_agent_1
    networks:
      p2p_net:
        ipv4_address: 172.18.0.2
      presentation_net:
    environment:
      - AGENT_ID=1
      - PEERS_LIMIT=2
      - REPORT_URL=http://172.20.0.3:8080/report
    ports:
      - "5001:5000/tcp"
      - "5001:5000/udp"
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  p2p_net:
    external: true
  presentation_net:
    external: true
