version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      presentation_net:
        ipv4_address: 172.20.0.2
    volumes:
      - neo4j-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      presentation_net:
        ipv4_address: 172.20.0.3

networks:
  presentation_net:
    external: true

volumes:
  neo4j-data: